[project]
name = "airport-wiki-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tim Yu", email = "yuyu.tim@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "more-itertools>=11.1.0",
    "mwparserfromhell>=0.7.2",
    "pytest>=9.1.1",
    "requests>=2.34.2",
]

[project.scripts]
airport-wiki-scraper = "airport_wiki_scraper:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
